### ISSUE TITLE
If we open FRONT Camera it Stops

### ISSUE THREAD

**Issue by tejas2** [husaynhakeem/android-face-detector#4]
java.lang.IllegalStateException: it.size must not be null
        at husaynhakeem.io.facedetectorapp.MainActivity$setupCamera$1.process(MainActivity.kt:28)
        at com.otaliastudios.cameraview.CameraView$Callbacks$13.run(CameraView.java:1721)
        at android.os.Handler.handleCallback(Handler.java:874)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:198)
        at android.os.HandlerThread.run(HandlerThread.java:65)

**Comment by Piyush0412** [comment]
Change Back to Front in this line
val lensFacing =
            savedInstanceState?.getSerializable(KEY_LENS_FACING) as Facing? ?: Facing.**_FRONT_**
